sudo: required
services:
    - docker

before_install:
    - docker build -t jvdrest/docker-react -f Dockerfile.dev .
 
script:
    - docker run jvdrest/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-425414716203"
    bucket_path: "docker-react"
    on:
        branche: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
        
        

