sudo: required
services:
    - docker

before_install:
    - docker build -t jvdrest/docker-react -f Dockerfile.dev .
 
script:
    - docker run jvdrest/docker-react npm run test -- --coverage
    
    
    
    

